name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: 'Tests on Node.js ${{ matrix.node-version }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: ['18', '20', '22']

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
