name: CI

on: [push, pull_request]

jobs:
  tests:
    name: 'Tests on Node.js ${{ matrix.node-version }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: ['18', '20', '22']

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - tests

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm install --frozen-lockfile

      - run: npx auto-dist-tag@1 --write

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
